# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-12 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogp', '0002_auto_20200206_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_time']},
        ),
    ]
