# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogp', '0003_auto_20200212_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
